CREATE DATABASE BookInfoDb
GO
USE BookInfoDb;
GO
CREATE TABLE Authors (
    Id INT IDENTITY(1,1) PRIMARY KEY,    
    FirstName VARCHAR(250) NOT NULL,
	LastName VARCHAR(250) NOT NULL
);
GO
CREATE TABLE Publishers (
    Id INT IDENTITY(1,1) PRIMARY KEY,    
    Name VARCHAR(250) NOT NULL
);
GO
CREATE TABLE Books (
    Id INT IDENTITY(1,1) PRIMARY KEY,    
    Title VARCHAR(MAX) NOT NULL,
	Price DECIMAL(10,2) NOT NULL,
	[Year] INT,
	ISBN VARCHAR(250),
	AuthorId INT NOT NULL FOREIGN KEY REFERENCES Authors(Id),
	PublisherId INT NOT NULL FOREIGN KEY REFERENCES Publishers(Id)
);
